spring:
    freemarker:
            suffix: .ftl
            templateEncoding: UTF-8
            templateLoaderPath: classpath:/templates/
    jmx:
         enabled: true
         default-domain: yaoyyboss

#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.ms.dao.model
doc:
    base:
        url: http://boss.mall.yaobest.com
biz:
    base:
         url: http://mall.yaobest.com
upload:
    path: /opt/resources/yaobest/
    url: http://mall.static.yaobest.com/

#logging:
#    level:
#        com.ms: DEBUG
#     path: @log.path@

server:
    error:
        whitelabel:
            enabled: false

sucai:
      log:
        enabled: true