spring:
    freemarker:
            suffix: .ftl
            templateEncoding: UTF-8
            templateLoaderPath: classpath:/templates/
    jmx:
         enabled: true
         default-domain: yaoyyboss

#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.ms.dao.model
doc:
    base:
        url: http://127.0.0.1:8189
biz:
    base:
         url: http://hztjn.free.natapp.cc
upload:
    path: E:/Program Files/Apache Software Foundation/Tomcat 8.5/webapps/ms-files/
    url: http://127.0.0.1:8189/ms-files/

#logging:
#    level:
#        com.ms: DEBUG
#     path: @log.path@

server:
    error:
        whitelabel:
            enabled: false
