
wechat:
  mp:
    appId: wx14385d863d69e1b7
    secret: d4624c36b6795d1d99dcf0547af5443d
    token: koabs
    partnerId: 1423682501
    partnerKey: 49a8a3011d2eb2734a5e88938bea8c1f



sms:
  apikey: 49a8a3011d2eb2734a5e88938bea8c1e
  serviceMobile: 18756759690

spring:
    dataSource:
        url: jdbc:mysql://192.168.1.52:3306/yaoyy?characterEncoding=utf-8
        username: yaoyy
        password: 123456
        driverClassName: com.mysql.jdbc.Driver

elasticsearch:
         host: 192.168.1.52
         port: 9300

redis:
    url: 127.0.0.1
    port: 6379

alipay:
    appId: appId
    privateKey: privateKey
    publicKey: publicKey
    sellerId: sellerId