
wechat:
  mp:
    appId: @wechat.mp.appid@
    secret: @wechat.mp.secret@
    token: @wechat.mp.token@



sms:
  apikey: 49a8a3011d2eb2734a5e88938bea8c1e
  serviceMobile: 18756759690

spring:
    dataSource:
        url: @spring.dataSource.url@
        username: @spring.dataSource.username@
        password: @spring.dataSource.password@
        driverClassName: com.mysql.jdbc.Driver

elasticsearch:
         host: @elasticsearch.host@
         port: @elasticsearch.port@

redis:
    url: @redis.url@
    port: @redis.port@