spring:
    freemarker:
            suffix: .ftl
            templateEncoding: UTF-8
            templateLoaderPath: classpath:/templates/
    jmx:
          enabled: true
          default-domain: yaoyybiz
    resources:
          chain:
              strategy:
                  content:
                        enabled: true
                        paths: /**

#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.ms.dao.model

doc:
   base:
       url: @doc.base.url@

upload:
    path: @pro.upload.path@
    url: @pro.upload.url@

#logging:
#    level:
#        com:
#          ms: DEBUG

server:
    error:
        whitelabel:
            enabled: false
#    context-path: /


