spring:
    dataSource:
        url: @spring.dataSource.url@
        username: @spring.dataSource.username@
        password: @spring.dataSource.password@
        driverClassName: com.mysql.jdbc.Driver
    freemarker:
            suffix: .ftl
            templateEncoding: UTF-8
            templateLoaderPath: classpath:/templates/
    jmx:
          enabled: true
          default-domain: yaoyybiz


#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.ms.dao.model
elasticsearch:
         host: @elasticsearch.host@
         port: @elasticsearch.port@

doc:
   base:
       url: @doc.base.url@

upload:
    path: @pro.upload.path@
    url: @pro.upload.url@

redis:
    url: @redis.url@
    port: @redis.port@

#logging:
#    level:
#        com:
#          ms: DEBUG

server:
    error:
        whitelabel:
            enabled: false
#    context-path: /

sms:
  apikey: 49a8a3011d2eb2734a5e88938bea8c1e


wechat:
    mp:
      appid: wx0b6c6683f64d3cc2
      secret: b52e6a9abba43685cf273c6028aec69d
      token: E10ADC3949BA59ABBE56E057F20F883E

