
wechat:
  mp:
    appId: wxa7f10cbf0dc060b9
    secret: fe68a821107c34bf9863348831e26755
    token: E10ADC3949BA59ABBE56E057F20F883E
    partnerId: 1423682501
    partnerKey: 49a8a3011d2eb2734a5e88938bea8c1f



sms:
  apikey: 49a8a3011d2eb2734a5e88938bea8c1e
  serviceMobile: 18756759690

spring:
    dataSource:
        url: jdbc:mysql://192.168.1.78:3306/yaoyy?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
        username: yaoyy
        password: 123456
        driverClassName: com.mysql.jdbc.Driver

elasticsearch:
         host: 192.168.1.78
         port: 9300

redis:
    url: 192.168.1.78
    port: 6379

alipay:
    appId: wxa7f10cbf0dc060b9
    privateKey: fe68a821107c34bf9863348831e26755
    publicKey: publicKey
    sellerId: sellerId