spring:
    freemarker:
            suffix: .ftl
            templateEncoding: UTF-8
            templateLoaderPath: classpath:/templates/
    jmx:
          enabled: true
          default-domain: yaoyybiz
    resources:
          chain:
              strategy:
                  content:
                        enabled: true
                        paths: /**

#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.ms.dao.model

doc:
   base:
       url: http://376161552.tunnel.2bdata.com

upload:
    path: E:/Program Files/Apache Software Foundation/Tomcat 8.5/webapps/ms-files/
    url: http://127.0.0.1:8188/ms-files/

#logging:
#    level:
#        com:
#          ms: DEBUG

server:
    error:
        whitelabel:
            enabled: false
#    context-path: /

